[project]
name = "artbuddy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.24",
    "matplotlib>=3.10.1",
    "openai>=1.76.0",
    "smolagents>=1.14.0",
    "typing>=3.10.0.0",
]
